
* Learn C!

** What is this?
This is a repository that aims to teach you the entire C programming
language, starting from the most basic concepts of programming and
ending with a comprehensive course on the entire POSIX standard
library.

This is aimed at people who know some programming concepts, such as
how to use a code editor, but do not know C specifically. This is not
an introduction to programming course.

This is primarily for MacOS and Linux users. Some of the libraries
will be different on Windows as it is not POSIX compliant.

** How do I use this?
Click on the green button labeled ~Code~ and choose ~Download as ZIP~.
Extract that ~ZIP~ archive into a directory.

To start learning, go into the ~intro~ folder and start at the first
lesson, labeled ~000~.

There are two main sections: the ~intro~ section and the ~library~
section. You need to do the ~intro~ section first to learn how to code
at all, then the ~library~ section teaches you about C's more advanced
functionality, such as reading and writing files.
